### ISSUE TITLE
TODO list for transition to gitflow

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#184]
A TODO list for the developers that will help clean and patch the project for it's transition to gitflow

 * [ ] Remove unused branches
 * [ ] Go over all issues and close those not relevant / fixed / duplicates
 * [ ] Merge finished pull requests
 * [ ] Update the contribution guide 
 * [ ] Removed unused files
 * [ ] Remove personal files from .gitignore
