### ISSUE TITLE
Sim TODO

### ISSUE THREAD

**Issue by RobinSchmid7** [jesseduffield/lazygit#4016]
- [ ] extend readme (how to use with and without  gpu)
- [ ] test manual controller
- [ ] run all options (gpu, no gpu, locally)
